### ISSUE TITLE
How to change port of UI

### ISSUE THREAD

**Issue by wardwygaerts** [tillsteinbach/CarConnectivity-plugin-webui#6]
I have already another container running on port 4000, so I tried to add `"port": "4001"` to the config json:
```
{
    "type": "webui",
    "config": {
        "username": "admin", // Admin username for login
        "password": "secret", // Admin password for login
        "port": "4001"
    }
}
```

But I get this error: (It's running fine without the `webui` config block)

```
20-02-2025 20:38:32 Traceback (most recent call last):
20-02-2025 20:38:32   File "/opt/venv/bin/carconnectivity-mqtt", line 8, in <module>
20-02-2025 20:38:32     sys.exit(main())
20-02-2025 20:38:32              ^^^^^^
20-02-2025 20:38:32   File "/opt/venv/lib/python3.12/site-packages/carconnectivity_mqtt/carconnectivity_mqtt_base.py", line 42, in main
20-02-2025 20:38:32     cli.main()
20-02-2025 20:38:32   File "/opt/venv/lib/python3.12/site-packages/carconnectivity/carconnectivity_base.py", line 79, in main
20-02-2025 20:38:32     car_connectivity = carconnectivity.CarConnectivity(config=config_dict, tokenstore_file=args.tokenfile, cache_file=args.cachefile)
20-02-2025 20:38:32                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20-02-2025 20:38:32   File "/opt/venv/lib/python3.12/site-packages/carconnectivity/carconnectivity.py", line 215, in __init__
20-02-2025 20:38:32     plugin: BasePlugin = plugin_class(plugin_id=plugin_id, car_connectivity=self, config=plugin_config['config'])
20-02-2025 20:38:32                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20-02-2025 20:38:32   File "/opt/venv/lib/python3.12/site-packages/carconnectivity_plugins/webui/plugin.py", line 34, in __init__
20-02-2025 20:38:32     if 'log_level' in self.active_config or not self.active_config['log_level']:
20-02-2025 20:38:32                                                 ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
20-02-2025 20:38:32 KeyError: 'log_level'
```

**Comment by tillsteinbach** [comment]
That is a bug, work-around is to add`"log_level": "error",` to the config

**Comment by tillsteinbach** [comment]
Should be fixed in `0.1.2`

**Comment by wardwygaerts** [comment]
Hi

I still have an issue with assiging a port:

```
02/24/2025 09:58:23 AMTraceback (most recent call last):
02/24/2025 09:58:23 AM  File "/opt/venv/bin/carconnectivity-mqtt", line 8, in <module>
02/24/2025 09:58:23 AM    sys.exit(main())
02/24/2025 09:58:23 AM              ^^^^^^
02/24/2025 09:58:23 AM   File "/opt/venv/lib/python3.12/site-packages/carconnectivity_mqtt/carconnectivity_mqtt_base.py", line 42, in main
02/24/2025 09:58:23 AM     cli.main()
02/24/2025 09:58:23 AM   File "/opt/venv/lib/python3.12/site-packages/carconnectivity/carconnectivity_base.py", line 79, in main
02/24/2025 09:58:23 AM     car_connectivity = carconnectivity.CarConnectivity(config=config_dict, tokenstore_file=args.tokenfile, cache_file=args.cachefile)
02/24/2025 09:58:23 AM                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02/24/2025 09:58:23 AM   File "/opt/venv/lib/python3.12/site-packages/carconnectivity/carconnectivity.py", line 215, in __init__
02/24/2025 09:58:23 AM     plugin: BasePlugin = plugin_class(plugin_id=plugin_id, car_connectivity=self, config=plugin_config['config'])
02/24/2025 09:58:23 AM                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02/24/2025 09:58:23 AM   File "/opt/venv/lib/python3.12/site-packages/carconnectivity_plugins/webui/plugin.py", line 45, in __init__
02/24/2025 09:58:23 AM     if not self.active_config['port'] or self.active_config['port'] < 1 or self.active_config['port'] > 65535:
02/24/2025 09:58:23 AM                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02/24/2025 09:58:23 AM TypeError: '<' not supported between instances of 'str' and 'int'
```

If I remove the port parameter and free up the port 4000 from my other container, everything is runing fine and I can reach the webui (only with network_mode on host)

**Comment by wardwygaerts** [comment]
My bad: I added the port as string, should be a number. Is working fine now!
